MainApp/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings


app_name = 'MainApp'

urlpatterns = [
    path('',views.index,name='index'),
    path('menu',views.menu,name='menu'),
    path('menu/<int:pizza_id>/',views.pizzas,name='pizzas'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pizzeria/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainApp.urls')),
]

MainApp/models.py
from django.db import models
from django.db.models import Model
# Create your models here.

# Create your models here.
class Pizza(models.Model):
    pizza_name = models.CharField(max_length=20)

    def __str__(self):
        return self.pizza_name

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza,on_delete=models.CASCADE)
    topping_name = models.CharField(max_length=20)

    class Meta:
        verbose_name = 'toppings'

    def __str__(self):
        return self.topping_name


class Image(Model):
    pizzaimg = models.ImageField(upload_to='photos',default='pizza.jpg')

MainApp/views.py
from django.shortcuts import render
from .models import *
# Create your views here.
def index(request):
    return render(request, 'MainApp/index.html')

def menu(request):
    menu = Pizza.objects.all()
    context = {'all_menu':menu}
    return render(request, 'MainApp/menu.html', context)

def pizzas(request,pizza_id):
    p = Pizza.objects.get(id=pizza_id)

    toppings = Topping.objects.filter(pizza=p)

    context = {'pizza':p,'toppings':toppings}

    return render(request, 'MainApp/pizzas.html', context)

MainApp/templates/mainapp/base.html
<p>
    <a href="{% url 'MainApp:index' %}">Pizzeria</a>
    <a href="{% url 'MainApp:menu' %}">Menu</a>

</p>
{% block content %}

{% endblock content %}

MainApp/templates/mainapp/index.html
{% extends "MainApp/base.html" %}



{% block content %}

<p style="text-align:center">

<p> Pizzeria </p>

<p>Order on Phone: xxx-xxx-xxxx</p>

<p><a href="{% url 'MainApp:menu' %}">Order on DoorDash </a></p>

<p> Welcome to Pizzeria </p>

{% load static %}
<img src="{% static 'image/BBQ-Chicken-PizzaIMG_0027.jpeg' %}" alt="pizza" width="300" height="600">

{% endblock content %}

MainApp/templates/mainapp/menu.html
{% extends "MainApp/base.html" %}

{% block content %}

<p> Check The Menu Here</p>

<ul>
    {% for menu in all_menu %}
    <li>
        <a href="{% url 'MainApp:menu' %}"> {{ menu }} </a>
    </li>

    {% empty %}
    <li>No pizza yet</li>
    {% endfor %}
</ul>


<p> Click on the pizza to see the detail</p>

{% endblock content %}

MainApp/templates/mainapp/pizzas.html
{% extends "MainApp/base.html" %}

{% block content %}

<p> {{ pizza }}</p>

<ul>
    {% for t in toppings %}

    <li>{{ t.topping_name }}</li>

    {% empty %}
    <li>No Image</li>
    {% endfor %}

</ul>

{% endblock content %}